### ISSUE TITLE
Would it be possible to create the same message for one member group?

### ISSUE THREAD

**Issue by marcuslelle** [oveleon/contao-member-notification#1]
My workaround would be "edit multiple", but a more editor friendly solution would be nice.
Funding could be made possible.

**Comment by zoglo** [comment]
**Closed as stale - [Request features](https://www.oveleon.de/contao-entwicklung.html#angebot-anfordern) if needed**

**Comment by zoglo** [comment]
See https://github.com/oveleon/contao-member-notification/issues/1#issuecomment-2142800660 @marcuslelle
