### ISSUE TITLE
"Forbidden" Error für Benutzer mit Zugriffsrechten auf das Modul

### ISSUE THREAD

**Issue by yomi-kurotani** [oveleon/contao-member-notification#2]
Für andere Contao Accounts, die kein Administrator sind, können keine Verwaltungsrechte für die Notifications eingestellt werden. Es erscheint nach Drücken auf das Glocken-Icon bei einem Mitglied sofort die Contao Fehlerseite mit "Forbidden - Not enough permissions to access the member notification module.". Für die Benutzergruppe habe ich testweise alles freigegeben, was möglich ist. Der Fehler tritt jedoch immernoch auf. 

Gibt es hier die Möglichkeit, auch anderen Benutzergruppen die Funktion freizuschalten?

**Comment by zoglo** [comment]
Hey @yomi-kurotani, it's not a bug but a missing feature.

Permissions are not yet coded into this plugin and we didn't plan this feature as of now.

You are welcome to create a PR.
Here's some help on how to start implementing them in a more modern way (Contao ^4.13)

**Button-Callbacks:**
* https://github.com/oveleon/contao-recommendation-bundle/blob/14e6657eb5bb439d8f792f2931c95e9fb3b1aa17/contao/dca/tl_recommendation_archive.php#L20-L28

**EventListener**
* https://github.com/oveleon/contao-recommendation-bundle/blob/main/src/EventListener/DataContainer/RecommendationArchiveListener.php

**Constants**
* https://github.com/oveleon/contao-recommendation-bundle/blob/main/src/Security/ContaoRecommendationPermissions.php

**Adding permissions to users and user_groups**
* https://github.com/oveleon/contao-recommendation-bundle/blob/main/contao/dca/tl_user.php
* https://github.com/oveleon/contao-recommendation-bundle/blob/main/contao/dca/tl_user_group.php

**Comment by zoglo** [comment]
**Closed as stale - [Request features](https://www.oveleon.de/contao-entwicklung.html#angebot-anfordern) if needed**
